runtime: nodejs18

env: standard

instance_class: F1

automatic_scaling:
  min_instances: 0
  max_instances: 2
  target_cpu_utilization: 0.65

env_variables:
  NODE_ENV: 'production'
  JWT_SECRET: 'SUBSTITUA_POR_SUA_CHAVE_SECRETA_FORTE'

handlers:
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301
